### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alex101087** [jmoor3/homeassistant-components#3]
Hi,

I wonder if you can help - I have NEVER installed a custom component and am having some issues.. I get the following log output:

`2018-09-14 15:16:21 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.bullfrog. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/srv/homeassistant/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/bullfrog.py", line 12, in <module>
    from custom_components.spaclient import SpaClient
  File "/home/homeassistant/.homeassistant/custom_components/spaclient.py", line 1, in <module>
    import crc8
ImportError: No module named 'crc8'
2018-09-14 15:16:21 ERROR (MainThread) [homeassistant.loader] Unable to find component bullfrog
2018-09-14 15:16:21 ERROR (MainThread) [homeassistant.setup] Setup failed for bullfrog: Component not found.`

So yeah, any help I would be forever grateful! :( 👍

**Comment by jmoor3** [comment]
You need the crc8 library to make it work https://pypi.org/project/crc8/. Try 

`pip install crc8`

**Comment by alex101087** [comment]
Hi mate,

Thanks for the advice - I have run this, it said it installed successfully and sudo reboot-ed but I still get an error message:

`2018-09-19 20:20:32 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.bullfrog. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 142, in get_component
    module = importlib.import_module(path)
  File "/srv/homeassistant/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/bullfrog.py", line 12, in <module>
    from custom_components.spaclient import SpaClient
  File "/home/homeassistant/.homeassistant/custom_components/spaclient.py", line 1, in <module>
    import crc8
ImportError: No module named 'crc8'
2018-09-19 20:20:33 ERROR (MainThread) [homeassistant.loader] Unable to find component bullfrog
2018-09-19 20:20:33 ERROR (MainThread) [homeassistant.setup] Setup failed for bullfrog: Component not found.`

Sorry to be a pain, any ideas? :(

Thanks again,

Alex

**Comment by alex101087** [comment]
Sorry, any ideas? I tried to install the crc8 library to no avail. :( Thanks 🙏🏽

Alex

**Comment by alex101087** [comment]
Any ideas? 😬 Thanks

**Comment by jmoor3** [comment]
You may need to switch user to the user that is running homeassistant - the crc8 installation needs to be in that user's python path. It's hard to know without understanding how you are running homeassistant.

**Comment by alex101087** [comment]
> You may need to switch user to the user that is running homeassistant - the crc8 installation needs to be in that user's python path. It's hard to know without understanding how you are running homeassistant.

Hi mate,

Thanks for the advice - I can't even remember how I installed homeassistant, whether it was in a virtualenv or whatever. Can I find out somehow?

It's a full GUI install of Linux with HA running on it.

I am so lost :(

Many, many apologies for my noobness.

Regards,

Alex

**Comment by alex101087** [comment]
> You may need to switch user to the user that is running homeassistant - the crc8 installation needs to be in that user's python path. It's hard to know without understanding how you are running homeassistant.

Oh my! I got it to work!

Thank you for the help.

One more thing I've just noticed - the target temperature is showing on HA as 24.5c/the actual temperature is showing as 25c, however the tub is actually on 38c/38c. Any ideas why it's so out?

Thanks again,

Alex :)

**Comment by netforceatg** [comment]
How did you get it to work?

I have the exact same issue. Running HA in a python virtual environment(under ubuntu), following this guide: https://www.home-assistant.io/docs/installation/raspberry-pi/

Have done the pip install crc8 after the following commands:
$ sudo -u homeassistant -H -s
$ source /srv/homeassistant/bin/activate

Any advice?

Here is my error log, loading the bullfrog component:

Error during setup of component bullfrog
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/bullfrog.py", line 70, in setup
    NETWORK = SpaData(host_ip)
  File "/home/homeassistant/.homeassistant/custom_components/bullfrog.py", line 51, in __init__
    self.spa = SpaClient(SpaClient.get_socket(host_ip))
  File "/home/homeassistant/.homeassistant/custom_components/spaclient.py", line 40, in get_socket
    SpaClient.s.connect((SpaClient.ip, 4257))
ConnectionRefusedError: [Errno 111] Connection refused
